### PR TITLE
Update rx versions in podspec

### PR DESCRIPTION
**Pull request by suyashcb**
1. Need this to prevent issues with `pod install`

### CODE REVIEW

**Review by johnnycoinbase — CHANGES_REQUESTED** [review]
What issue were you seeing with `pod install`? Can you post it in the description or here?

**Comment by suyashcb** [comment]
```
[!] CocoaPods could not find compatible versions for pod “RxSwift”:
  In snapshot (Podfile.lock):
    RxSwift (= 4.3.1, ~> 4.0, ~> 4.3.0)
  In Podfile:
    CBCore (from `git@github.com:CoinbaseWallet/CBCore.git`) was resolved to 0.1.0, which depends on
      RxSwift (~> 4.4.0)
    CBDatabase (from `git@github.com:CoinbaseWallet/CBDatabase.git`) was resolved to 0.1.0, which depends on
      RxSwift (< 5.0.0, >= 4.4.0)
    RxSwift
Specs satisfying the `RxSwift, RxSwift (= 4.3.1, ~> 4.0, ~> 4.3.0), RxSwift (< 5.0.0, >= 4.4.0), RxSwift (~> 4.4.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by johnnycoinbase** [comment]
Is that running `pod install` in this repo, or for the wallet app? I'm unable to repro on either. Can you try running `pod repo update` and see if that changes anything for you?

**Comment by suyashcb** [comment]
OHH nevermind, I got it, it was because ~>4.3.0 was specified in the podfile.lock (I'm in the consumer app btw).

**Pull request closed without merging**
